#FROM python:3.7-alpine
FROM linuxserver/code-server:latest

ENV PUID=1000 
ENV PGID=1000 
ENV TZ=Europe/London 
ENV PASSWORD=demodemo
#ENV SUDO_PASSWORD=demodemo
#ENV PROXY_DOMAIN=code-server.my.domain `#optional` \
#  -p 8443:8443 \
#VOLUME /path/to/appdata/config:/config 
#  --restart unless-stopped \
#  linuxserver/code-server